### ISSUE TITLE
App Crash on startup

### ISSUE THREAD

**Issue by Bugreporter48** [deHank/findroid#3]
**Describe the bug**
The app crash when launching the app

**To Reproduce**
I will edit this later

**Device info**
 - Device: [ Google Pixel 5]
 - Android version: [14]
 - App version: [I will edit this later]
 - Jellyfin version: [I will edit this later]

**Additional context**
It might have something to do with running a custom ROM that's called GrapheneOS since it hasn't any google services installed

**Logs**`
```
type: crash
osVersion: google/redfin/redfin:14/UP1A.231005.007/2023101300:user/release-keys
package: dev.jdtech.jellyfin.debug:22
process: dev.jdtech.jellyfin.debug
processUptime: 620 + 91 ms
installer: com.android.packageinstaller

java.lang.RuntimeException: Unable to start activity ComponentInfo{dev.jdtech.jellyfin.debug/dev.jdtech.jellyfin.MainActivity}: java.lang.RuntimeException: com.google.android.gms.cast.framework.ModuleUnavailableException: com.google.android.gms.dynamite.DynamiteModule$LoadingException: No acceptable module com.google.android.gms.cast.framework.dynamite found. Local version is 0 and remote version is 0.
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3793)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3933)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2450)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8199)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
Caused by: java.lang.RuntimeException: com.google.android.gms.cast.framework.ModuleUnavailableException: com.google.android.gms.dynamite.DynamiteModule$LoadingException: No acceptable module com.google.android.gms.cast.framework.dynamite found. Local version is 0 and remote version is 0.
	at com.google.android.gms.cast.framework.CastContext.getSharedInstance(com.google.android.gms:play-services-cast-framework@@21.3.0:11)
	at dev.jdtech.jellyfin.MainActivity.setupActivity(MainActivity.kt:69)
	at dev.jdtech.jellyfin.MainActivity.onCreate(MainActivity.kt:64)
	at android.app.Activity.performCreate(Activity.java:8651)
	at android.app.Activity.performCreate(Activity.java:8629)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1461)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3775)
	... 12 more
Caused by: com.google.android.gms.cast.framework.ModuleUnavailableException: com.google.android.gms.dynamite.DynamiteModule$LoadingException: No acceptable module com.google.android.gms.cast.framework.dynamite found. Local version is 0 and remote version is 0.
	at com.google.android.gms.internal.cast.zzaf.zzf(com.google.android.gms:play-services-cast-framework@@21.3.0:7)
	at com.google.android.gms.internal.cast.zzaf.zza(com.google.android.gms:play-services-cast-framework@@21.3.0:1)
	at com.google.android.gms.cast.framework.CastContext.<init>(com.google.android.gms:play-services-cast-framework@@21.3.0:4)
	at com.google.android.gms.cast.framework.CastContext.getSharedInstance(com.google.android.gms:play-services-cast-framework@@21.3.0:10)
	... 18 more
Caused by: com.google.android.gms.dynamite.DynamiteModule$LoadingException: No acceptable module com.google.android.gms.cast.framework.dynamite found. Local version is 0 and remote version is 0.
	at com.google.android.gms.dynamite.DynamiteModule.load(com.google.android.gms:play-services-basement@@18.0.0:65)
	at com.google.android.gms.internal.cast.zzaf.zzf(com.google.android.gms:play-services-cast-framework@@21.3.0:2)
	... 21 more`


```

**Comment by deHank** [comment]
Reading through this, I think it is due to graphene OS not having any google services since the app uses com.google.android.gms.cast.framework and it says in the error your version is 0.

**Comment by Bugreporter48** [comment]
I thought that was the problem but I wasn't sure if that was the cause for it but I'll try again next week.
